[package]
name = "a2a_tictactoe"
version = "0.1.0"
authors = ["Devin Fisher <devin.fisher@evernym.com>"]
edition = "2018"

[dependencies]
eventsourcing = "0.1.1"
eventsourcing-derive = "0.1.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
